sudo: false
language: scala
dist: trusty

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION ci

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

jdk:
  - oraclejdk8

env:
  global:
    - COURSIER_PROGRESS=0
